name: pr-preview
on: pull_request_target
jobs:
  build-upload:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
      GH_PR_NUM:   ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      # Yes, we really want to checkout the PR
      - run: |
          git fetch origin pull/$GH_PR_NUM/head:tmp
          git checkout tmp

      - run: |
          git rev-parse origin/main
          git rev-parse HEAD
          git rev-parse origin/main..HEAD
          git log origin/main..HEAD --format="%b"

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable Corepack
        shell: bash
        run: corepack enable
      - uses: actions/cache@v4
        id: yarn-cache
        name: Load Yarn cache
        with:
          path: |
            .yarn/cache
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-
      - name: Install dependencies
        shell: bash
        run: yarn install --immutable --network-timeout 100000
      - run: yarn build
        name: Build component groups
      - uses: actions/cache@v4
        id: docs-cache
        name: Load webpack cache
        with:
          path: '.cache'
          key: ${{ runner.os }}-v4-${{ hashFiles('yarn.lock') }}
      - run: yarn build:docs
        name: Build docs
      - name: Deploy preview to surge
        if: env.SURGE_LOGIN != '' && env.SURGE_TOKEN != ''
        run: |
          npx surge packages/module/public --domain pr-${{ github.event.number }}-widgetized-dashboard.surge.sh
      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome
      - name: a11y tests
        run: yarn serve:docs & yarn test:a11y
